### GENERAL Section ###############################################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: FIMOcello

  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

### Detailed Configuration ########################################################################

  packages: !include_dir_named packages

### Options Section ###############################################################################

# Enables the frontend
frontend:

# enables HASSIO
hassio:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - sonos
    - samsung_tv
    - harmony
    - apple_tv
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:


panel_iframe:
  router:
    title: 'Router'
    url: 'http://192.168.1.1'
  portainer:
    title: 'Portainer'
    url: 'http://hassio.fritz.box:9000'
  nodered:
    title: 'Node-Red'
    url: 'http://hassio.fritz.box:1880'
  noderednas:
    title: 'Node-Red NAS'
    url: 'http://cellonas.fritz.box:1880'



