### GENERAL Section ###############################################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: FIMOcello

  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich


### Detailed Configuration ########################################################################

  packages: !include_dir_named packages



### Options Section ###############################################################################

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# enables HASSIO
hassio:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:
discovery:
  ignore:
    - sonos
    - samsung_tv
    - harmony
    - apple_tv
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# keep track of events on a outside DB
recorder:
  db_url: !secret recorder_db_url
  #purge_days: 5

################################################
## History Setup
################################################
history:
  include:
    domains:
      - sensor
      - switch
      - binary_sensor.balcony_door
      - binary_sensor.motion01
      - binary_sensor.motion02
      - binary_sensor.office_window
  exclude:
    entities:
      - group.weekly_forecast
      - group.weather_overview
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4n_metric 
      - sensor.pws_weather_1d_metric
      - sensor.pws_temp_high_record_c
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_low_1d_c
      - sensor.pws_temp_low_record_c
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_mm
      - sensor.pws_wind_1d_kph      

################################################
## Logbook Setup
################################################
logbook:
  include:
    domains:
      - sensor
      - switch
  exclude:
    entities:
      - group.weekly_forecast
      - group.weather_overview



panel_iframe:
  router:
    title: 'Router'
    url: 'http://192.168.1.1'
  portainer:
    title: 'Portainer'
    url: 'http://192.168.1.139:9000'
  nodered:
    title: 'Node-Red'
    url: 'http://192.168.1.139:1880'



