################################################################
## Packages / Groups / Devices
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/devices'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################


    group.kitchen_devices:
      <<: *customize
      friendly_name: "Kitchen Devices"
      icon: mdi:chili-mild

    group.office_devices:
      <<: *customize
      friendly_name: "Office Devices"
      icon: mdi:printer


################################################
## Group
################################################

group:
  kitchen_devices:
    view: no
    entities:
      - switch.mystrom_01
  office_devices:
    view: no
    entities:
      - switch.mystrom_02
      
