################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.dining_room_lights:
      <<: *customize
      friendly_name: "Dining Room Lights"
      # hidden: true
      icon: mdi:lightbulb

    group.kitchen_lights:
      <<: *customize
      friendly_name: "Kitchen Lights"
      icon: mdi:lightbulb

    group.studio_lights:
      <<: *customize
      friendly_name: "Studio Lights"
      # hidden: true
      icon: mdi:lightbulb

    group.living_room_lights:
      <<: *customize
      friendly_name: "Living Room Lights"
      # hidden: true
      icon: mdi:lightbulb

    group.bed_room_lights:
      <<: *customize
      friendly_name: "Bedroom Lights"
      # hidden: true
      icon: mdi:lightbulb

    group.guest_room_lights:
      <<: *customize
      friendly_name: "Guest Room Lights"
      # hidden: true
      icon: mdi:lightbulb

    group.office_lights:
      <<: *customize
      friendly_name: "Office Lights"
      # hidden: true
      icon: mdi:lightbulb

    group.entrance_lights:
      <<: *customize
      friendly_name: "Entrance Lights"
      # hidden: true
      icon: mdi:lightbulb

################################################
## Group
################################################

group:

  dining_room_lights:
    view: no
    entities:
      - light.sonoff_switch_diningroom
      - light.bloom_diningroom


  entrance_lights:
    view: no
    entities:
      - light.spot_entrance_middle
      - light.spot_entrance_mirror
      - light.spot_entrance_stair      


  kitchen_lights:
    view: no
    entities:
      - light.spot_kitchen_storeroom
      - light.spot_kitchen_fridge
      - light.spot_kitchen_cabinet

  studio_lights:
    view: no
    entities:
      - light.sonoff_led_studio

  living_room_lights:
    view: no
    entities:
      - switch.light_livingroom_front
      - switch.light_livingroom_back
      - light.strip_dining_room

  bed_room_lights:
    view: no
    entities:
      - light.light_bedroom_fimo
      - light.bloom_bedroom
      - light.spot_bedroom
      - switch.mystrom_00

  guest_room_lights:
    view: no
    entities:
      - light.strip_guestroom
      - light.bloom_guestroom

  office_lights:
    view: no
    entities:
      - light.sonoff_led_office
      - light.bloom_gallery

  house:
    view: no
    entities:
      - group.lightgroup
      - group.mediagroup
      - input_boolean.dining_room_lights_flag
      - input_boolean.entrance_lights_flag
      - input_boolean.kitchen_lights_flag
      - input_boolean.studio_lights_flag
      - input_boolean.living_room_lights_flag
      - input_boolean.bed_room_lights_flag
      - input_boolean.guest_room_lights_flag
      - input_boolean.office_lights_flag
      

