################################################################
## Packages / History
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'history'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## History
################################################

history:
  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - group
      - lock
      - sensor
  exclude:
    domains:
      - automation
      - media_player
      - light
      - script
      - switch
      - zone
    entities:
      - group.house
      - group.all_lights
      - group.all_switches
      - group.kitchen
      - group.tesla
      - group.mediagroup
      - group.radiostations
      - group.weather
      - group.weather_general
      - group.weather_overview
      - group.weather_wunderground
      - group.weekly_forecast
      - sensor.pws_feelslike_c
      - switch.rfswitch_white_03
      - sensor.fimocello_home_tado_bridge_status
      - sensor.pws_weather
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4n_metric 
      - sensor.pws_weather_1d_metric
      - sensor.pws_temp_high_record_c
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_low_1d_c
      - sensor.pws_temp_low_record_c
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_mm
      - sensor.pws_wind_1d_kph      
      - sensor.season
      - sensor.studio_link
      - sensor.studio_overlay
      - sensor.studio_power
      - sensor.studio_tado_mode
      - sensor.office_link
      - sensor.office_overlay
      - sensor.office_power
      - sensor.office_tado_mode
      - sensor.sun
      
