################################################################
## Packages / HTTP
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'http'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## HTTP
################################################

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  login_attempts_threshold: 3
  ip_ban_enabled: true
  use_x_forwarded_for: true
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://hub.docker.com


