################################################################
## Packages / Input Boolean
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'inputboolean'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false


################################################
## Group States (for Alexa Automations)
################################################
input_boolean:

  dining_room_lights_flag:
    name: Status of diningroom lights
    initial: off
    icon: mdi:flag-variant
  
  entrance_lights_flag:
    name: Status of entrance lights
    initial: off
    icon: mdi:flag-variant
  
  kitchen_lights_flag:
    name: Status of kitchen lights
    initial: off
    icon: mdi:flag-variant
  
  studio_lights_flag:
    name: Status of studio lights
    initial: off
    icon: mdi:flag-variant
  
  living_room_lights_flag:
    name: Status of livingroom lights
    initial: off
    icon: mdi:flag-variant
  
  bed_room_lights_flag:
    name: Status of bedroom lights
    initial: off
    icon: mdi:flag-variant
  
  guest_room_lights_flag:
    name: Status of guestroom lights
    initial: off
    icon: mdi:flag-variant
  
  office_lights_flag:
    name: Status of office lights
    initial: off
    icon: mdi:flag-variant
  
