################################################################
## Packages / Logger
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'logger'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Logger
################################################

################################################
## Logging during Debug Phase
################################################

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    # debug
    homeassistant.components.rflink: debug

    # info
    homeassistant.bootstrap: info
    homeassistant.components.websocket_api: info
    homeassistant.core: info
    homeassistant.helpers.script: info

    # warn

    homeassistant.components.api: warn
    homeassistant.components.automation: warn
    homeassistant.components.binary_sensor: warn
    homeassistant.components.climate: warn
    homeassistant.components.device_tracker: warn
    homeassistant.components.http: warn
    homeassistant.components.light: warn
    homeassistant.components.lock: warn
    homeassistant.components.media_player: warn
    homeassistant.components.mqtt: warn
    homeassistant.components.notify: warn
    homeassistant.components.recorder: warn
    homeassistant.components.sensor: warn
    homeassistant.components.switch: warn
    homeassistant.components.telegram_bot: warn
    homeassistant.components.xiaomi: warn
    homeassistant.helpers: warn
    homeassistant.loader: warn

