
################################################################
## Packages / MQTT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mqtt'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false


################################################
## MQTT Broker
################################################
mqtt:
  broker: cellonas.fritz.box 
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: fimocello-hassio
  keepalive: 60

