################################################################
## Packages / Recorder
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'recorder'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Recorder
################################################

recorder:
  db_url: !secret recorder_db_url
  #purge_days: 5

  include:
    domains:
      - binary_sensor
      - climate
      - device_tracker
      - light
      - lock
      - sensor
      - switch
    entities:
      - group.bed_room_lights
      - group.dining_room_lights
      - group.entrance_lights
      - group.guest_room_lights
      - group.kitchen_lights
      - group.kitchen_devices
      - group.living_room_lights
      - group.office_lights
      - group.studio_lights      
  exclude:
    domains:
      - automation
      - group
      - media_player
      - sensor
      - script
      - zone
    entities:
      - sensor.fimocello_home_tado_bridge_status
      - sensor.pws_weather
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4n_metric 
      - sensor.pws_weather_1d_metric
      - sensor.pws_temp_high_record_c
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_low_1d_c
      - sensor.pws_temp_low_record_c
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_mm
      - sensor.pws_wind_1d_kph      
      - sensor.season
      - sensor.studio_link
      - sensor.studio_overlay
      - sensor.studio_power
      - sensor.studio_tado_mode
      - sensor.office_link
      - sensor.office_overlay
      - sensor.office_power
      - sensor.office_tado_mode
      - sensor.sun

