################################################################
## Packages / Telegram
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'telegram'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    # automation.forward_persistent_notifications:
    #   <<: *customize
    #   friendly_name: "Forward Persistent Notifications"
    #   icon: mdi:message-text

    # automation.telegram_restart:
    #   <<: *customize
    #   friendly_name: "Telegram: Restart"
    #   icon: mdi:power

    # automation.telegram_roll:
    #   <<: *customize
    #   friendly_name: "Telegram: Roll"
    #   icon: mdi:dice-multiple

################################################
## Automation
################################################

# automation:
  # - alias: forward_persistent_notifications
  #   initial_state: 'on'
  #   trigger:
  #     - platform: event
  #       event_type: call_service
  #       event_data:
  #         domain: persistent_notification
  #         service: create
  #   action:
  #     - service: notify.telegram
  #       data_template:
  #         message: >-
  #           {% set message = trigger.event.data.service_data.message %}
  #           {% if 'login attempt' in message|lower %}
  #             {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
  #           {% else %}
  #             {{ message }}
  #           {% endif %}

  # - alias: telegram_restart
  #   trigger:
  #     - platform: event
  #       event_type: telegram_command
  #       event_data:
  #         command: '/restart'
  #   action:
  #     - service: notify.telegram
  #       data:
  #         message: "Restarting Home Assistant, please wait..."
  #     - service: script.restart_hass

  # - alias: telegram_roll
  #   trigger:
  #     - platform: event
  #       event_type: telegram_command
  #       event_data:
  #         command: '/roll'
  #   action:
  #     - service: notify.cellerich
  #       data_template:
  #         message: >-
  #           {% set sides = (trigger.event.data.args|default)[0]|default(6) %}
  #           I rolled a {{ sides|string ~ '-sided die' if sides != 6 else 'die' }} and got {{ range(1, sides + 1)|random }}.

################################################
## Telegram Bot - just to broadcast
################################################

telegram_bot:
  platform: broadcast
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id_cellerich
    - !secret telegram_chat_id_fimo


################################################
## Notify
################################################

notify:
  - name: cellerich
    platform: telegram
    chat_id: !secret telegram_chat_id_cellerich

  - name: fimo
    platform: telegram
    chat_id: !secret telegram_chat_id_fimo
