################################################################
## Packages / Weather
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.weather_general:
      <<: *customize
      friendly_name: "General"

    group.weather_wunderground:
      <<: *customize
      friendly_name: "Weather Underground"

    group.weather_overview:
      <<: *customize
      friendly_name: "Daily Forecast"

    group.weekly_forecast:
      <<: *customize
      friendly_name: "Weekly Forecast"

    ################################################
    ## Sensor
    ################################################

    sensor.pws_feelslike_c:
      <<: *customize
      friendly_name: "Feels Like"
      icon: mdi:thermometer

    sensor.pws_heat_index_c:
      <<: *customize
      friendly_name: "Heat Index"
      icon: mdi:thermometer

    sensor.pws_precip_today_metric:
      <<: *customize
      friendly_name: "Precipitation"
      icon: mdi:weather-rainy

    sensor.pws_relative_humidity:
      <<: *customize
      friendly_name: "Humidity"
      icon: mdi:water-percent

    sensor.pws_temp_c:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer

    sensor.pws_weather:
      <<: *customize
      friendly_name: "Current Conditions"

    sensor.pws_wind_degrees:
      <<: *customize
      friendly_name: "Wind Direction"
      icon: mdi:compass-outline

    sensor.season:
      <<: *customize
      friendly_name: "Season"
      icon: mdi:weather-snowy-rainy
 

################################################
## Group
################################################

group:
  weather_general:
    control: hidden
    entities:
      - sun.sun
      - sensor.season

  weather_wunderground:
    control: hidden
    entities:
      - sensor.pws_feelslike_c
      - sensor.pws_heat_index_c
      - sensor.pws_relative_humidity
      - sensor.pws_precip_today_metric
      - sensor.pws_temp_c
      - sensor.pws_weather

  weekly_forecast:
    control: hidden
    entities:
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4n_metric      

  weather_overview:
    control: hidden
    entities:
      - sensor.pws_weather_1d_metric
      - sensor.pws_temp_high_record_c
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_c
      - sensor.pws_temp_low_1d_c
      - sensor.pws_temp_low_record_c
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_mm
      - sensor.pws_wind_kph
      - sensor.pws_wind_1d_kph      
      - sensor.pws_wind_degrees
      - sensor.pws_wind_gust_kph

################################################
## Sensor
################################################

sensor:

  - platform: wunderground
    api_key: !secret weatherunderground_api_key
    monitored_conditions:
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - temp_low_record_c
      - precip_1d
      - precip_1d_mm
      - wind_kph
      - wind_degrees
      - wind_gust_kph
      - wind_1d_kph
      - feelslike_c
      - precip_today_metric
      - relative_humidity
      - weather
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - weather_4d_metric
      - weather_4n_metric      

  - platform: season
    type: astronomical